### ISSUE TITLE
error in yolo/convert_tflite

### ISSUE THREAD

**Issue by ivost** [tetutaro/object_detection_tflite#1]
I am trying to convert yolo weights following the instructions
I got this error

```
post-training... (99/100)
Traceback (most recent call last):
  File "/home/ivo/github/object_detection_tflite/yolo/convert_tflite.py", line 247, in <module>
    export_tflite(model=model)
  File "/home/ivo/github/object_detection_tflite/yolo/convert_tflite.py", line 188, in export_tflite
    load_darknet_weights(model=model, model_keras=model_keras)
  File "/home/ivo/github/object_detection_tflite/yolo/convert_tflite.py", line 70, in load_darknet_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose(
ValueError: cannot reshape array of size 14646 into shape (64,32,3,3)
```
Indeed 64x32x3x3 = 18432

```
        # tf shape (height, width, in_dim, out_dim)
        conv_weights = conv_weights.reshape(conv_shape).transpose(
            [2, 3, 1, 0]
        )
```

**Comment by tetutaro** [comment]
Thank you for your report and apologize for late reply, @ivost .
To be honest, I had already abandoned to maintain the conversion code in **this repository**.
Instead of that, I created new repository for converting pre-trained weights of YOLO to various frameworks.
[tetutaro/yolo_various_framework](https://github.com/tetutaro/yolo_various_framework)
Of course, the above repository is not completed yet, but I am modifying codes of this repository to use the TensorFlow Lite binary created in the above repository **now**.
